indent_width: 2
continuation_indent_width: 2
align_args: false
break_after_function_call_lp: true
break_before_functioncall_rp: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
align_parameter: false
single_quote_to_double_quote: true
spaces_before_call: 1
align_table_field: false
