#!/usr/bin/env bash

sudo pacman -S --noconfirm git
cd $HOME
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

cd $HOME/.dotfiles/bin

./install-dependencies
./python-packages
./volta
./lf-dependencies
./neomutt-dependencies
./bat-themes
./bat-extras
./install-vim-plugins
./git
