#!/bin/sh

# PACKER_COMPILED=~/.config/nvim/plugin/packer_compiled.vim
# PLUGINS=~/.local/share/nvim/site/pack/packer

# if [[ -f "$PACKER_COMPILED" ]]; then
#     rm $PACKER_COMPILED
# fi

# if [[ -e "$PLUGINS" ]]; then
#     rm -rf $PLUGINS
# fi
