#!/bin/bash

# put this script in /usr/lib/systemd/system-sleep/ or /lib/systemd/system-sleep/example.sh for debian/ubuntu

case $1/$2 in
  pre/*)
    echo "Going to $2..."
    # Place your pre suspend commands here, or `exit 0` if no pre suspend action required
    ;;
  post/*)
    echo "Waking up from $2..."

    # also need export display for this to work
    DISPLAY=:0.0 ; export DISPLAY
    # the sleep is very important so that xmodmap runs after hal
    /bin/su brian -c "sleep 4; /bin/bash /home/brian/.dotfiles/bin/keymappings"
    ;;
esac
