#! /bin/bash


# -----------------------------------------------------
# ------------------- Bspwm Settings ------------------
# -----------------------------------------------------
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4.5
bspc config window_gap          35
# bspc config window_gap          50

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a sxiv state=tiled
bspc rule -a mpv state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc config focused_border_color "#928374"
bspc config normal_border_color "#504945"

# -----------------------------------------------------
# ------------------- Miscellaneous -------------------
# -----------------------------------------------------

~/.config/polybar/launch.sh

# set display scale
xrandr --output eDP1 --scale 1x1

# set wallpaper
feh --bg-scale ~/Pictures/geometric_background.png
# feh --bg-scale ~/.config/awesome/themes/gruvbox/wallpapers/wall.png

# set correct pulseaudio settings
/home/brian/.config/yadm/dotfiles/bin/pulseaudio &

# -----------------------------------------------------
# ------------------- Autostart apps ------------------
# -----------------------------------------------------
picom &
nm-applet &
xfce4-power-manager

# -----------------------------------------------------
# ------------------- Miscellaneous Settings ----------
# -----------------------------------------------------

# set touchpad options
xinput set-prop 13 "libinput Tapping Enabled" 1
xinput set-prop 13 "libinput Natural Scrolling Enabled" 1
xinput set-prop 13 "libinput Disable While Typing Enabled" 0
# allow two finger click
xinput set-prop 13 "libinput Click Method Enabled" 0 1

# set keyrepeat (first number is time for key repeat, second is speed)
xset r rate 310 60

# start keymappings
/home/brian/.config/yadm/dotfiles/bin/keymappings

# Change from ugly 'X' cursor when hovering over background
xsetroot -cursor_name left_ptr
